nelmio_api_doc:
  documentation:
    schemes: [http, https]
    host: localhost:8000
    info:
      title: Learnfiy
      description: Edeco Learnfiy User Management EndPoints
      version: 1.0.0
      areas:
        path_patterns: # an array of regexps
        - ^/(?!api)
        # host_patterns:
        #   - ^api\.